version: "3"

services:

    db:
        container_name: mysql
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        env_file: .env
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --lower_case_table_names=1
        volumes:
            - ./data:/var/lib/mysql